### ISSUE TITLE
[Firebase] Unable to resume activity {com.vsevolodganin.clicktrack/com.vsevolodganin.clicktrack.MainActivity}: v9.u: lateinit property navigation has not been initialized

### ISSUE THREAD

**Issue by vganin** [vganin/click-track#5]
https://console.firebase.google.com/u/0/project/click-track-a6453/crashlytics/app/android:com.vsevolodganin.clicktrack/issues/da6df7c11eb9fcbfda0a49c4c61e7987
```
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.vsevolodganin.clicktrack/com.vsevolodganin.clicktrack.MainActivity}: v9.u: lateinit property navigation has not been initialized
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4898)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4931)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
Caused by v9.u: lateinit property navigation has not been initialized
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1$1$1.invoke(InjectMainActivityComponent.kt:103)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1$1$1.invoke(InjectMainActivityComponent.kt:102)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1$1.invoke(InjectMainActivityComponent.kt:102)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1$1.invoke(InjectMainActivityComponent.kt:93)
       at com.vsevolodganin.clicktrack.ScreenViewModelFactory.create(ScreenViewModelFactory.java:30)
       at com.vsevolodganin.clicktrack.di.module.ViewModelModule$provideScreenStackState$2.invoke(ViewModelModule.kt:58)
       at com.vsevolodganin.clicktrack.di.module.ViewModelModule$provideScreenStackState$2.invoke(ViewModelModule.kt:58)
       at com.arkivanov.decompose.router.children.DefaultChildItemFactory.invoke(DefaultChildItemFactory.kt:32)
       at com.arkivanov.decompose.router.children.ChildrenNavigator.restore(ChildrenNavigator.kt:85)
       at com.arkivanov.decompose.router.children.ChildrenNavigator.<init>(ChildrenNavigator.kt:47)
       at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children(ChildrenFactory.kt:80)
       at com.arkivanov.decompose.router.children.ChildrenFactoryKt.children$default(ChildrenFactory.kt:61)
       at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:91)
       at com.arkivanov.decompose.router.stack.ChildStackFactoryKt.childStack(ChildStackFactory.kt:40)
       at com.vsevolodganin.clicktrack.di.module.ViewModelModule$DefaultImpls.provideScreenStackState(ViewModelModule.java:84)
       at com.vsevolodganin.clicktrack.di.component.MainActivityComponent.provideScreenStackState(MainActivityComponent.kt:27)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1.invoke(InjectMainActivityComponent.kt:93)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2$1.invoke(InjectMainActivityComponent.kt:92)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2.invoke(InjectMainActivityComponent.kt:92)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1$2.invoke(InjectMainActivityComponent.kt:91)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.vsevolodganin.clicktrack.drawer.DrawerViewModelImpl$1.invoke(DrawerViewModelImpl.kt:40)
       at com.vsevolodganin.clicktrack.drawer.DrawerViewModelImpl$1.invoke(DrawerViewModelImpl.kt:39)
       at com.arkivanov.essenty.lifecycle.LifecycleExtKt$subscribe$1.onCreate(LifecycleExt.kt:16)
       at com.arkivanov.essenty.lifecycle.AndroidLifecycleObserver.onCreate(AndroidExt.kt:56)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
       at com.arkivanov.essenty.lifecycle.EssentyLifecycleInterop.subscribe(AndroidExt.kt:32)
       at com.arkivanov.essenty.lifecycle.LifecycleExtKt.subscribe(LifecycleExt.kt:38)
       at com.arkivanov.essenty.lifecycle.LifecycleExtKt.subscribe$default(LifecycleExt.kt:6)
       at com.vsevolodganin.clicktrack.drawer.DrawerViewModelImpl.<init>(DrawerViewModelImpl.kt:39)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1.invoke(InjectMainActivityComponent.kt:84)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1$1.invoke(InjectMainActivityComponent.kt:83)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1.invoke(InjectMainActivityComponent.kt:83)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1$1.invoke(InjectMainActivityComponent.kt:80)
       at com.vsevolodganin.clicktrack.di.module.ViewModelModule$DefaultImpls.provideDrawerViewModel(ViewModelModule.java:66)
       at com.vsevolodganin.clicktrack.di.component.MainActivityComponent.provideDrawerViewModel(MainActivityComponent.kt:27)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1.invoke(InjectMainActivityComponent.kt:80)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1$1.invoke(InjectMainActivityComponent.kt:79)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1.invoke(InjectMainActivityComponent.kt:79)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1$1$1.invoke(InjectMainActivityComponent.kt:77)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1.invoke(InjectMainActivityComponent.kt:77)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$navigation$1.invoke(InjectMainActivityComponent.kt:72)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent.getNavigation(InjectMainActivityComponent.kt:72)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent.access$getNavigation(InjectMainActivityComponent.kt:64)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$intentProcessor$1.invoke(InjectMainActivityComponent.kt:473)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent$intentProcessor$1.invoke(InjectMainActivityComponent.kt:471)
       at me.tatarka.inject.internal.LazyMap.get(LazyMap.java:16)
       at com.vsevolodganin.clicktrack.di.component.InjectMainActivityComponent.getIntentProcessor(InjectMainActivityComponent.kt:471)
       at com.vsevolodganin.clicktrack.MainActivity.onNewIntent(MainActivity.kt:59)
       at android.app.Activity.performNewIntent(Activity.java:8250)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1431)
       at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1444)
       at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3973)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4881)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4931)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Comment by vganin** [comment]
Steps:
1. Enable "Don't Keep Activities" in Developer Options
2. Open app
3. Navigate to launcher by swiping up but don't close the app
4. Open app again by clicking app's icon in launcher
