### ISSUE TITLE
Calls to setForegroundAsync() must complete before a ListenableWorker signals completion of work by returning an instance of Result.

### ISSUE THREAD

**Issue by vganin** [vganin/click-track#56]
https://console.firebase.google.com/project/click-track-a6453/crashlytics/app/android:com.vsevolodganin.clicktrack/issues/ac3a90ffdb0030ab4fcbc42b89d87233?time=last-seven-days&sessionEventKey=6667CB0201F000016AE9E6522E805161_1957538465199163851
```
# Crashlytics - Stack trace
# Application: com.vsevolodganin.clicktrack
# Platform: android
# Version: 1.2.0 (20240603) (67)
# Issue: ac3a90ffdb0030ab4fcbc42b89d87233
# Session: 6667CB0201F000016AE9E6522E805161_DNE_0_v2
# Date: Tue Jun 11 2024 05:09:00 GMT+0100 (British Summer Time)

Non-fatal Exception: l5.c: Failed to export track
       at com.vsevolodganin.clicktrack.utils.log.LoggerImpl$NonFatalException.<init>(LoggerImpl.java:32)
       at com.vsevolodganin.clicktrack.utils.log.LoggerImpl.logError(LoggerImpl.kt:25)
       at com.vsevolodganin.clicktrack.export.ExportToAudioFile.export(ExportToAudioFile.kt:149)
       at com.vsevolodganin.clicktrack.export.ExportToAudioFile$export$1.invokeSuspend(ExportToAudioFile.kt:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:585)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

Caused by java.lang.IllegalStateException: Calls to setForegroundAsync() must complete before a ListenableWorker signals completion of work by returning an instance of Result.
       at androidx.work.impl.utils.WorkForegroundUpdater$1.run(WorkForegroundUpdater.java:95)
       at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by vganin** [comment]
Doesn't reproduce anymore, closing.

**Comment by vganin** [comment]
Updated repro link, now it's non-fatal: https://console.firebase.google.com/project/click-track-a6453/crashlytics/app/android:com.vsevolodganin.clicktrack/issues/6d9098632cce145740027d036f643a4d?time=last-thirty-days&sessionEventKey=669B8BF3001700013D9CE64CC3C956C4_1972106736741545140

**Comment by vganin** [comment]
Looks like there might be a problem with Jetpack Worker library - `setForegroundAsync` checks if current work is still valid (not finished, cancelled, etc.), but that is no synchronized with worker's main thread. So, e.g. there might be non-adversarial occasions of this exception being throws when work is in cancelling process. I'll this to rest, let's see if library updates can solve it. If not, will give it another look.
